=== Larusso/modeler/generator.dtd
<?xml version='1.0' encoding='UTF-8'?>
		<!ENTITY % lang "lang CDATA '*'">

		<!ELEMENT model (class|iface|include|types)*>

		<!ELEMENT class (implements|property|method|extends)*>
		<!ATTLIST class
				%lang;
				type CDATA #REQUIRED>

		<!ELEMENT iface (property|method|extends)*>
		<!ATTLIST iface
				%lang;
				type CDATA #REQUIRED>

		<!ELEMENT property EMPTY>
		<!ATTLIST property
				%lang;
				name CDATA #REQUIRED
				type CDATA #REQUIRED>

		<!ELEMENT extends EMPTY>
		<!ATTLIST extends
				%lang;
				type CDATA #REQUIRED>

		<!ELEMENT method (param)*>
		<!ATTLIST method
				%lang;
				name CDATA #REQUIRED
				returns CDATA #REQUIRED>

		<!ELEMENT param EMPTY>
		<!ATTLIST param
				type CDATA #REQUIRED
				name CDATA #REQUIRED>

		<!ELEMENT implements EMPTY>
		<!ATTLIST implements
				%lang;
				iface CDATA #REQUIRED>

		<!ELEMENT include EMPTY>
		<!ATTLIST include
				path CDATA #REQUIRED>

		<!ELEMENT types (type)*>

		<!ELEMENT type (target)*>
		<!ATTLIST type
				name CDATA #REQUIRED>

		<!ELEMENT target EMPTY>
		<!ATTLIST target
				%lang;
				value CDATA #REQUIRED>

=== Larusso/modeler/test-resources/test-model-filter-tag-lang.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "http://www.modeler.tslarusso.de/generator.dtd">
<model xmlns="http://www.modeler.tslarusso.de/modelerSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.modeler.tslarusso.de/modeler.xsd">

	<class type="NormalClass">
		<method returns="void" name="actionscriptMethod" lang="as3">
			<param name="param1" type="NormalClass"/>
			<param name="param2" type="NormalClass"/>
			<param name="param3" type="NormalClass"/>
		</method>

		<method returns="void" name="javaMethod" lang="java">
			<param name="param1" type="NormalClass"/>
			<param name="param2" type="NormalClass"/>
			<param name="param3" type="NormalClass"/>
			<param name="param4" type="NormalClass"/>
		</method>
	</class>
</model>

=== Larusso/modeler/test-resources/model/decorator/class-decorator-class-with-decorator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "http://www.modeler.tslarusso.de/generator.dtd">
<model xmlns="http://www.modeler.tslarusso.de/modelerSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.modeler.tslarusso.de/modeler.xsd">

	<iface type="de.example.interfaces.IDescriptor">
		<property name="name" type="String"/>
		<property name="uuid" type="int"/>
		<method returns="void" name="getStuff"/>
	</iface>

	<class type="de.example.model.DecorateeClass">
		<implements iface="de.example.interfaces.IDescriptor"/>
	</class>

	<class type="de.example.model.DecorateeClass2">
		<implements iface="de.example.interfaces.IDescriptor"/>
		<decorates name="decoratee1" type="de.example.model.DecorateeClass"/>
		<property name="type" type="String"/>
	</class>

	<class type="de.example.model.DecoratorClass">
		<decorates name="decoratee2" type="de.example.model.DecorateeClass2"/>
	</class>
</model>

=== Larusso/modeler/test-resources/testModel2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "http://www.modeler.tslarusso.de/generator.dtd">
<model xmlns="http://www.modeler.tslarusso.de/modelerSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.modeler.tslarusso.de/modeler.xsd">
	<types>
		<type name="void">
			<target lang="java" value="void"/>
			<target lang="as3" value="void"/>
		</type>
		<type name="object">
			<target lang="java" value="Map"/>
			<target lang="as3" value="Object"/>
		</type>
		<type name="objectarray">
			<target lang="java" value="Object[]"/>
			<target lang="as3" value="Array"/>
		</type>
		<type name="uint">
			<target lang="java" value="int"/>
			<target lang="as3" value="uint"/>
		</type>
		<type name="int">
			<target lang="java" value="int"/>
			<target lang="as3" value="int"/>
		</type>
		<type name="long">
			<target lang="java" value="long"/>
			<target lang="as3" value="Number"/>
		</type>
		<type name="objectlong">
			<target lang="java" value="Long"/>
			<target lang="as3" value="Number"/>
		</type>
		<type name="integer">
			<target lang="java" value="Integer"/>
			<target lang="as3" value="int"/>
		</type>
		<type name="char">
			<target lang="java" value="char"/>
			<target lang="as3" value="char"/>
		</type>
		<type name="float">
			<target lang="java" value="float"/>
			<target lang="as3" value="Number"/>
		</type>
		<type name="double">
			<target lang="java" value="double"/>
			<target lang="as3" value="Number"/>
		</type>
		<type name="boolean">
			<target lang="java" value="boolean"/>
			<target lang="as3" value="Boolean"/>
		</type>
		<type name="string">
			<target lang="java" value="String"/>
			<target lang="as3" value="String"/>
		</type>
		<type name="list">
			<target lang="java" value="List&lt;?&gt;"/>
			<target lang="as3" value="ArrayCollection"/>
		</type>
		<type name="objectlist">
			<target lang="java" value="List&lt;Object&gt;"/>
			<target lang="as3" value="mx.collections.ArrayCollection"/>
		</type>
		<type name="arraylist">
			<target lang="java" value="List&lt;Object&gt;"/>
			<target lang="as3" value="mx.collections.ArrayCollection"/>
		</type>

		<type name="set">
			<target lang="java" value="Set&lt;?&gt;"/>
			<target lang="as3" value="mx.collections.ArrayCollection"/>
		</type>
		<type name="collection">
			<target lang="java" value="Collection&lt;?&gt;"/>
			<target lang="as3" value="mx.collections.ArrayCollection"/>
		</type>
		<type name="map">
			<target lang="java" value="Map&lt;String,?&gt;"/>
			<target lang="as3" value="Object"/>
		</type>
		<type name="map(string,string)">
			<target lang="java" value="Map&lt;String,String&gt;"/>
			<target lang="as3" value="Object"/>
		</type>
		<type name="wildcard">
			<target lang="java" value="Object"/>
			<target lang="as3" value="*"/>
		</type>
		<type name="bytearray">
			<target lang="java" value="byte[]"/>
			<target lang="as3" value="ByteArray"/>
		</type>
		<type name="date">
			<target lang="java" value="Date"/>
			<target lang="as3" value="Date"/>
		</type>

		<type name="bitmap">
			<target lang="as3" value="flash.display.Bitmap"/>
		</type>

		<type name="asyncMessage">
			<target lang="as3" value="mx.messaging.messages.AsyncMessage"/>
		</type>

		<type name="message">
			<target lang="as3" value="Object"/>
		</type>
	</types>

	<class type="JavaTestClass" lang="java"/>
	<class type="JavaTestClass2" lang="java"/>
	<class type="JavaTestClass3" lang="java"/>

	<class type="ASTestClass" lang="as3"/>
	<class type="ASTestClass2" lang="as3"/>

	<class type="NormalClass">
		<method returns="void" name="asMethod1" lang="as3"/>
		<method returns="void" name="asMethod2" lang="as3"/>
		<method returns="void" name="commonMethod"/>
		<method returns="void" name="javaMethod1" lang="java"/>
		<method returns="void" name="javaMethod2" lang="java"/>
		<method returns="void" name="javaMethod3" lang="java"/>
	</class>
	<class type="NormalClass2"/>
</model>

=== Larusso/modeler/test-resources/testModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "generator.dtd">
<model>
	<iface type="ISimpleInterface">
		<property type="string" name="name"/>
	</iface>

	<class type="SimpleClass">
		<property name="name" type="string"/>
	</class>

	<iface type="IBaseClass"/>

	<class type="BaseClass">
		<extends type="SimpleClass"/>
		<implements iface="IBaseClass"/>

		<property type="de.example.IClassType" name="type"/>
		<property type="collection" name="list"/>

		<method name="getName" returns="string"/>
		<method name="getType" returns="de.example.IClassType"/>

		<method name="combine" returns="IBaseTestClass">
			<param name="first" type="IBaseTestClass"/>
			<param name="second" type="IBaseTestClass"/>
		</method>
	</class>

	<iface type="IExtendedClass">
		<method name="copy" returns="void"/>
	</iface>

	<class type="ExtendedClass">
		<extends type="BaseClass"/>
		<implements iface="ISimpleInterface"/>
		<implements iface="IExtendedClass"/>
		<property name="power" type="string"/>
	</class>

	<class type="ExtendedClass2">
		<implements iface="IExtendedClass"/>
		<method name="copy" returns="void"/>
	</class>

	<iface type="IMultiInheritance">
		<extends type="ISimpleInterface"/>
		<extends type="IExtendedClass"/>
	</iface>

	<class type="ExtendsLibraryClass">
		<extends type="mx.collections.ArrayCollection"/>
		<property type="string" name="name"/>
	</class>
</model>

=== Larusso/modeler/test-resources/test-model-class-implements-interface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "http://www.modeler.tslarusso.de/generator.dtd">
<model xmlns="http://www.modeler.tslarusso.de/modelerSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.modeler.tslarusso.de/modeler.xsd">


	<iface type="IFace1">
		<property name="property1" type="int"/>
		<property name="property2" type="int"/>
		<property name="property3" type="int"/>

		<method returns="void" name="get1"/>
		<method returns="void" name="get2"/>
	</iface>

	<class type="Class1">
		<implements iface="IFace1"/>
	</class>
</model>

=== Larusso/modeler/model/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "generator.dtd">
<model>
	<iface type="de.tslarusso.interfaces.IServerProfileInfo">
		<property type="int" name="profileId"/>
		<property type="string" name="name"/>
		<property type="com.domain.Sex" name="sex"/>
		<property type="long" name="birthday"/>
		<property type="string" name="city"/>
		<property type="string" name="firstName"/>
		<property type="string" name="lastName"/>
		<property type="string" name="password"/>
		<property type="de.tslarusso.CustomerStatus" name="customerStatus"/>
		<property type="string" name="email"/>
		<property type="objectlong" name="emailver"/>
		<property type="boolean" name="emailBounceStatus"/>
		<property type="string" name="newEmail"/>
		<property type="boolean" name="newEmailBounceStatus"/>
		<property type="string" name="cafftag"/>
		<property type="uint" name="domainId"/>
		<property type="string" name="locale"/>
		<property type="boolean" name="newsletterEnabled"/>
		<property type="set(integer)" name="roleIds"/>
		<property type="int" name="styleSlotCount" bindable="true"/>
		<property type="int" name="sessionCount" bindable="true"/>
	</iface>

	<class type="de.tslarusso.model.ServerProfileInfo">
		<extends type="de.tslarusso.model.ServerProfileInfo2"/>
		<implements iface="de.tslarusso.interfaces.IServerProfileInfo"/>
		<property type="int" name="profileId"/>
		<property type="string" name="name"/>
		<property type="com.domain.Sex" name="sex"/>
		<property type="long" name="birthday"/>
		<method name="copy" returns="void">
			<param name="param1" type="de.tslarusso.interfaces.IServerProfileInfo"/>
			<param name="param2" type="de.tslarusso.interfaces.IServerProfileInfo"/>
		</method>
	</class>

	<class type="de.tslarusso.model.ServerProfileInfo2">
		<implements iface="de.tslarusso.interfaces.IServerProfileInfo"/>
	</class>
</model>
