=== Larusso/modeler/schema/generator.dtd
<?xml version='1.0' encoding='UTF-8'?>
		<!ENTITY % lang "lang CDATA '*'">

		<!ELEMENT model (class|iface|entity|include|types)*>

		<!ELEMENT entity (implements|property|method|extends|const|doc|annotate)*>
		<!ATTLIST entity
				%lang;
				type CDATA #REQUIRED
				templateId CDATA #REQUIRED
                exclude (true|false) "false">

		<!ELEMENT class (implements|property|method|extends|const|decorates|doc|annotate)*>
		<!ATTLIST class
				%lang;
				type CDATA #REQUIRED
				templateId CDATA "class"
                exclude (true|false) "false">

		<!ELEMENT iface (property|method|extends|doc|annotate)*>
		<!ATTLIST iface
				%lang;
				type CDATA #REQUIRED
				templateId CDATA "iface"
                exclude (true|false) "false">

		<!ELEMENT property (doc|annotate)*>
		<!ATTLIST property
				%lang;
				name CDATA #REQUIRED
				type CDATA #REQUIRED
                readOnly (true|false) "false">

		<!ELEMENT const (#PCDATA)>
		<!ATTLIST const
				%lang;
				name CDATA #REQUIRED
				type CDATA #REQUIRED>

		<!ELEMENT doc (#PCDATA)>
		<!ATTLIST doc
				%lang;>

        <!ELEMENT annotate (#PCDATA)>
        <!ATTLIST annotate
                %lang;>

		<!ELEMENT extends EMPTY>
		<!ATTLIST extends
				%lang;
				type CDATA #REQUIRED>

		<!ELEMENT decorates EMPTY>
		<!ATTLIST decorates
				%lang;
				type CDATA #REQUIRED
				name CDATA #REQUIRED
				prefix CDATA ""
                readOnly (true|false) "false">

		<!ELEMENT method (param|doc|annotate)*>
		<!ATTLIST method
				%lang;
				name CDATA #REQUIRED
				returns CDATA #REQUIRED>

		<!ELEMENT param EMPTY>
		<!ATTLIST param
				type CDATA #REQUIRED
				name CDATA #REQUIRED>

		<!ELEMENT implements EMPTY>
		<!ATTLIST implements
				%lang;
				iface CDATA #REQUIRED>

		<!ELEMENT include EMPTY>
		<!ATTLIST include
				path CDATA #REQUIRED>

		<!ELEMENT types (type)*>

		<!ELEMENT type (target)*>
		<!ATTLIST type
				name CDATA #REQUIRED>

		<!ELEMENT target EMPTY>
		<!ATTLIST target
				%lang;
				value CDATA #REQUIRED>

=== Larusso/modeler/test-resources/model/annotation/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE model SYSTEM "http://www.modeler.tslarusso.de/generator.dtd">
<model xmlns="http://www.modeler.tslarusso.de/modelerSchema"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.modeler.tslarusso.de/modeler.xsd">

    <iface type="ISimpleInterface">
        <annotate lang="as3"><![CDATA[[Include(type="lala")]]></annotate>
        <annotate><![CDATA[[Test Test]]></annotate>
        <property name="name" type="String">
            <annotate lang="as3"><![CDATA[[RemoteClass]]></annotate>
        </property>
        <method returns="String" name="getName">
            <annotate lang="as3"><![CDATA[[Depricated]]></annotate>
            <param name="type" type="int"/>
            <param name="inst" type="Object"/>
        </method>
    </iface>

    <class type="SimpleClass">
        <annotate lang="as3"><![CDATA[[RemoteClass]]></annotate>
        <annotate lang="as3"><![CDATA[[SpecialClass]]></annotate>
        <annotate lang="java"><![CDATA[[@override]]></annotate>

        <property name="name" type="String">
            <annotate lang="as3"><![CDATA[[RemoteClass]]></annotate>
        </property>
        <method returns="String" name="getName">
            <annotate lang="as3"><![CDATA[[Depricated]]></annotate>
            <param name="type" type="int"/>
            <param name="inst" type="Object"/>
        </method>
    </class>

</model>
